### PR TITLE
Update README with pipeline documentation.

### PR DESCRIPTION
**Pull request by dspalmer99**
Signed-off-by: Daniel Palmer <dan.palmer@anchore.com>

### CODE REVIEW

**Review by zhill — APPROVED** [review]
Looks good to me. Would like @nightfurys to take a look as well.

**Comment by dspalmer99** [comment]
@nightfurys A kind reminder to give this pr a thumbs up if it looks good to you now.

**Comment by rmkanda** [comment]
Can we also include the example of how to pass credentials as well?

image

**Review by nightfurys — APPROVED** [review]
@dspalmer99, the example using annotations is neat. Can you also add an example using a credentials? I think that's a far more used workflow

**Comment by dspalmer99** [comment]
Thanks! I've made that change.

**Comment by nightfurys** [comment]
lgtm

**Pull request merged**
