### PR TITLE
Add 'engineRetries' to pipeline sample snippet

### PR DESCRIPTION
**Pull request by timwebster9**
You need to include 'engineRetries' if using a Pipeline script.  If not, you end up with the following error:

`2017-10-14T09:57:37.611 ERROR  AnchoreWorker   Failed to run Anchore gates due to an unexpected error
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.anchore.jenkins.plugins.anchore.BuildWorker.runGatesEngine(BuildWorker.java:397)
	at com.anchore.jenkins.plugins.anchore.BuildWorker.runGates(BuildWorker.java:362)
	at com.anchore.jenkins.plugins.anchore.AnchoreBuilder.perform(AnchoreBuilder.java:312)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

### CODE REVIEW

**Comment by nightfurys** [comment]
@timwebster9, thank you for submitting the pull request! Failing to run the plugin due to missing retry value seems like a bug to me. While the user should be able to override the retries, I think the plugin should assume a sane default if its not explicitly overwritten. I'm looking into it.

**Comment by timwebster9** [comment]
Yes agreed - was going to suggest a default as well.  I realise there are issues with the snippet generator, but if that was working it would help as well.  The reason I submitted a PR for the docs is that seems to be the only reference on the entire internet on how to use it with pipeline :-)

**Comment by nightfurys** [comment]
Yep, makes sense. Getting the snippet generator to work correctly would make getting started with the plugin so much more easier. Its a known issue and I'm working on it. Will keep you posted.

**Comment by nightfurys** [comment]
Fixed the plugin to assume defaults displayed on the snippet generator page. Also fixed plugin to work with snippet generator correctly, the generator should output a programmatically accurate pipeline script for invoking anchore plugin with the selected configuration

**Pull request closed without merging**
