### PR TITLE
Added trend graph and report link on job page

### PR DESCRIPTION
**Pull request by georgwolf**
As discussed in #2 this is a separate PR just for the trend graph and report link on the project page.

Note that due to [JENKINS-28479](https://issues.jenkins-ci.org/browse/JENKINS-28479) at least one successful build with an Anchore Report (i.e. at least Unstable) is required for the graph to show up.

### CODE REVIEW

**Comment by nightfurys** [comment]
@georgwolf, I tested this with both passing and failing (due to anchore policy result) build results. The trend line looks correct in both cases. Hovering over the line/area displays the count and clicking navigates to the build quickly. Nicely done!

I noticed that if a build is deleted, the trend line up to that build is lost. This loss is apparent after the completion of a new build. I was able to reproduce this by deleting a random build. After triggering a new build, the trend line up until the deleted build was no longer visible. I'm not familiar with Jenkins project actions related classes but I would suspect an issue with previous build results lookup logic. Deleting builds may not be a very common use case but I thought I'd mention my observations here just in case its an easy fix.

**Comment by georgwolf** [comment]
Hi @nightfurys,
the logic for getting the previous build was inspired by the jUnit plugin which is showing the same behavior, also other analysis plugins like Open tasks lose the trend up to the deleted build. However I did take a further look, as it of course would be nice to skip deleted builds. Looks like it is not necessary (anymore) to check for the LazyBuildMixin explicitly as hudson.model.AbstractBuild.getPreviousBuild() already handles this (at least in the referenced baseline Jenkins version of 1.625.3) and skips deleted builds properly. warnings-ng-plugin also now only relies on AbstractBuild.getPreviousBuild() only, so this seems to be the right way now.
I also set a more sensible default for the maximum number of builds shown in the trend graph.

**Comment by nightfurys** [comment]
Hello @georgwolf, that fixed the issue over deleted builds. I noticed an "Enlarge" hyperlink right below the trend line that doesn't seem to be functional. Any idea what it's meant for?

**Comment by georgwolf** [comment]
Hi @nightfurys, the link takes you to a larger graph. It was simply covered by the Stage view for Pipeline projects, Freestyle didn't have the issue. But simple to fix by adding a z-index, so it's now clickable in Pipelines as well. Let me know if there's another issue

**Comment by nightfurys** [comment]
I've only been testing it with a pipeline and everything looks good. Thank you for the nifty new feature and the follow up fixes @georgwolf

**Comment by nightfurys** [comment]
One last thing before I merge the commits - the commits have to be signed off by including the following text in your contribution commit message:
`Signed-off-by: Joan Doe <joan.doe@email.com>`
This message can be entered manually, or if you have configured git with the correct user.name and user.email, you can use the -s option to git commit to automatically include the signoff message.

**Comment by georgwolf** [comment]
Hi @nightfurys, Sign off has been added.

**Pull request merged**
